<?php

namespace Eni\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReponseProposeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseProposeeRepository extends EntityRepository
{
}
