<?php

namespace Eni\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository {

	public function getUtilisateurParNomPrenom($nom, $prenom = null) {
		$oQueryBuilder = $this->createQueryBuilder("u");
		$oQueryBuilder->where($oQueryBuilder->expr()->eq('u.nom', ':nom'))
				->setParameter("nom", $nom);
		if (!is_null($prenom)) {
			$oQueryBuilder->andWhere($oQueryBuilder->expr()->eq('u.prenom', ':prenom'))
					->setParameter("prenom", $prenom);
		}
		return $oQueryBuilder->getQuery()->getResult();
	}
}
